services:
  db-taiso:
    image: postgres:17.2
    container_name: db-taiso
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /postgres/pgdata
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ./storage/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres  || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 50
  go-gorm-taiso:
    build:
      context: ./docker/go
    container_name: go-gorm-taiso
    tty: true
    # ports:
    #   - 8080:8080
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/go-gorm-taiso
      - ./storage/go:/go
    working_dir: /go-gorm-taiso
    depends_on:
      db-taiso:
        condition: service_healthy
